In [1]:
import pandas as pd
import yfinance as yf

In [32]:
stockData = pd.read_csv("constituents-financials_csv.csv")
stockData

,Symbol,Name,Sector,Price,Price/Earnings,Dividend Yield,Earnings/Share,52 Week Low,52 Week High,Market Cap,EBITDA,Price/Sales,Price/Book,SEC Filings
0,MMM,3M Company,Industrials,222.89,24.31,2.332862,7.92,259.77,175.490,138721055226,9.048000e+09,4.390271,11.34,http://www.sec.gov/cgi-bin/browse-edgar?action...
1,AOS,A.O. Smith Corp,Industrials,60.24,27.76,1.147959,1.70,68.39,48.925,10783419933,6.010000e+08,3.575483,6.35,http://www.sec.gov/cgi-bin/browse-edgar?action...
2,ABT,Abbott Laboratories,Health Care,56.27,22.51,1.908982,0.26,64.60,42.280,102121042306,5.744000e+09,3.740480,3.19,http://www.sec.gov/cgi-bin/browse-edgar?action...
3,ABBV,AbbVie Inc.,Health Care,108.48,19.41,2.499560,3.29,125.86,60.050,181386347059,1.031000e+10,6.291571,26.14,http://www.sec.gov/cgi-bin/browse-edgar?action...
4,ACN,Accenture plc,Information Technology,150.51,25.47,1.714470,5.44,162.60,114.820,98765855553,5.643228e+09,2.604117,10.62,http://www.sec.gov/cgi-bin/browse-edgar?action...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
500,XYL,Xylem Inc.,Industrials,70.24,30.94,1.170079,1.83,76.81,46.860,12915021000,7.220000e+08,2.726209,5.31,http://www.sec.gov/cgi-bin/browse-edgar?action...
501,YUM,Yum! Brands Inc,Consumer Discretionary,76.30,27.25,1.797080,4.07,86.93,62.850,27003303098,2.289000e+09,6.313636,212.08,http://www.sec.gov/cgi-bin/browse-edgar?action...
502,ZBH,Zimmer Biomet Holdings,Health Care,115.53,14.32,0.794834,9.01,133.49,108.170,24454698119,2.007400e+09,3.164895,2.39,http://www.sec.gov/cgi-bin/browse-edgar?action...
503,ZION,Zions Bancorp,Financials,50.71,17.73,1.480933,2.60,55.61,38.430,10670678640,0.000000e+00,3.794579,1.42,http://www.sec.gov/cgi-bin/browse-edgar?action...
504,ZTS,Zoetis,Health Care,71.51,32.80,0.682372,1.65,80.13,52.000,35991109776,1.734000e+09,9.280896,18.09,http://www.sec.gov/cgi-bin/browse-edgar?action...

In [33]:
stockData.columns

Index(['Symbol', 'Name', 'Sector', 'Price', 'Price/Earnings', 'Dividend Yield',
       'Earnings/Share', '52 Week Low', '52 Week High', 'Market Cap', 'EBITDA',
       'Price/Sales', 'Price/Book', 'SEC Filings'],
      dtype='object')

In [34]:
#I Decided to try out taking out some of the columsn and creating a new dataframe with what I thought was kinda important -JB
sp500 = stockData.drop(columns = ['52 Week Low', '52 Week High', 'SEC Filings', 'Price', 'Dividend Yield', 'Market Cap', 'EBITDA', 'Price/Sales', 'Price/Book'], axis = 1)
sp500

,Symbol,Name,Sector,Price/Earnings,Earnings/Share
0,MMM,3M Company,Industrials,24.31,7.92
1,AOS,A.O. Smith Corp,Industrials,27.76,1.70
2,ABT,Abbott Laboratories,Health Care,22.51,0.26
3,ABBV,AbbVie Inc.,Health Care,19.41,3.29
4,ACN,Accenture plc,Information Technology,25.47,5.44
...,...,...,...,...,...
500,XYL,Xylem Inc.,Industrials,30.94,1.83
501,YUM,Yum! Brands Inc,Consumer Discretionary,27.25,4.07
502,ZBH,Zimmer Biomet Holdings,Health Care,14.32,9.01
503,ZION,Zions Bancorp,Financials,17.73,2.60
504,ZTS,Zoetis,Health Care,32.80,1.65

I realized when trying to pull financals that there are some companies in the dataframe that are no longer on the sp500 due to being pulled or aquired so I went through and figured out which ones so that I can remove them and reduce the processing time

In [35]:
symbolsNotFound = ['ATVI', 'AET', 'AFL', 'ALXN', 'AGN', 'ADS', 'ALL', 'AXP', 'AIG', 'AMP', 'ABC', 'APC', 'ANDV', 'ANTM', 'ARNC', 'AIZ', 'BHGE', 'BLL', 'BAC', 'BBT', 'BRK.B', 'BHF', 'BF.B', 'CA', 'COG', 'COF', 'CBG', 'CBS', 'CELG', 'CTL', 'CERN', 'SCHW', 'CB', 'CI', 'XEC', 'CINF', 'C', 'CFG', 'CTXS', 'CMA', 'CXO', 'CSRA', 'DFS', 'DISCA', 'DISCK', 'DISH', 'DWDP', 'DPS', 'DRE', 'ETFC', 'EVHC', 'RE', 'ESRX', 'FB', 'FITB', 'FISV', 'FLIR', 'FBHS', 'GGP', 'GS', 'HRS', 'HIG', 'HUM', 'HBAN', 'INFO', 'JEC', 'JPM', 'KSU', 'KEY', 'LB', 'LLL', 'LUK', 'LNC', 'L', 'MTB', 'MET', 'KORS', 'MON', 'MS', 'MYL', 'NAVI', 'NFX', 'NLSN', 'NBL', 'NTRS', 'PBCT', 'PKI', 'PNC', 'PCLN', 'PFG', 'PGR', 'PRU', 'RJF', 'RTN', 'RHT', 'RF', 'COL', 'SCG', 'SNI', 'STT', 'SYMC', 'SYF', 'BK', 'TRV', 'TIF', 'TWX', 'TMK', 'TSS', 'USB', 'UTX', 'UNM', 'VAR', 'VIAB', 'WFC', 'HCN', 'WLTW', 'WYN', 'XLNX', 'XL', 'ZION']
indeciesToDrop = [sp500[sp500["Symbol"].isin(symbolsNotFound)].index]

for index in indeciesToDrop:
    sp500 = sp500.drop(index=index)

---
This is more of a work area :) FYI

In [62]:
msft = yf.Ticker("MSFT")
print(msft.balance_sheet.index)

Index(['Ordinary Shares Number', 'Share Issued', 'Net Debt', 'Total Debt',
       'Tangible Book Value', 'Invested Capital', 'Working Capital',
       'Net Tangible Assets', 'Capital Lease Obligations',
       'Common Stock Equity', 'Total Capitalization',
       'Total Equity Gross Minority Interest', 'Stockholders Equity',
       'Gains Losses Not Affecting Retained Earnings',
       'Other Equity Adjustments', 'Retained Earnings', 'Capital Stock',
       'Common Stock', 'Total Liabilities Net Minority Interest',
       'Total Non Current Liabilities Net Minority Interest',
       'Other Non Current Liabilities', 'Tradeand Other Payables Non Current',
       'Non Current Deferred Liabilities', 'Non Current Deferred Revenue',
       'Non Current Deferred Taxes Liabilities',
       'Long Term Debt And Capital Lease Obligation',
       'Long Term Capital Lease Obligation', 'Long Term Debt',
       'Current Liabilities', 'Other Current Liabilities',
       'Current Deferred Liabilities', 'Current Deferred Revenue',
       'Current Debt And Capital Lease Obligation', 'Current Debt',
       'Pensionand Other Post Retirement Benefit Plans Current',
       'Payables And Accrued Expenses', 'Payables', 'Total Tax Payable',
       'Income Tax Payable', 'Accounts Payable', 'Total Assets',
       'Total Non Current Assets', 'Other Non Current Assets',
       'Investments And Advances', 'Long Term Equity Investment',
       'Goodwill And Other Intangible Assets', 'Other Intangible Assets',
       'Goodwill', 'Net PPE', 'Accumulated Depreciation', 'Gross PPE',
       'Leases', 'Other Properties', 'Machinery Furniture Equipment',
       'Buildings And Improvements', 'Land And Improvements', 'Properties',
       'Current Assets', 'Other Current Assets', 'Hedging Assets Current',
       'Inventory', 'Finished Goods', 'Work In Process', 'Raw Materials',
       'Receivables', 'Accounts Receivable',
       'Allowance For Doubtful Accounts Receivable',
       'Gross Accounts Receivable',
       'Cash Cash Equivalents And Short Term Investments',
       'Other Short Term Investments', 'Cash And Cash Equivalents',
       'Cash Equivalents', 'Cash Financial'],
      dtype='object')

In [18]:
msftIncomeStatement = msft.income_stmt
msftIncomeStatement

,2023-06-30,2022-06-30,2021-06-30,2020-06-30
Tax Effect Of Unusual Items,-2850000.0,43420000.0,180160797.164637,4760000.0
Tax Rate For Calcs,0.19,0.13,0.138266,0.17
Normalized EBITDA,105155000000.0,99905000000.0,83831000000.0,68395000000.0
Total Unusual Items,-15000000.0,334000000.0,1303000000.0,28000000.0
Total Unusual Items Excluding Goodwill,-15000000.0,334000000.0,1303000000.0,28000000.0
Net Income From Continuing Operation Net Minority Interest,72361000000.0,72738000000.0,61271000000.0,44281000000.0
Reconciled Depreciation,13861000000.0,14460000000.0,11686000000.0,12796000000.0
Reconciled Cost Of Revenue,65863000000.0,62650000000.0,52232000000.0,46078000000.0
EBITDA,105140000000.0,100239000000.0,85134000000.0,68423000000.0
EBIT,91279000000.0,85779000000.0,73448000000.0,55627000000.0
Net Interest Income,1026000000.0,31000000.0,-215000000.0,89000000.0
Interest Expense,1968000000.0,2063000000.0,2346000000.0,2591000000.0
Interest Income,2994000000.0,2094000000.0,2131000000.0,2680000000.0
Normalized Income,72373150000.0,72447420000.0,60148160797.164635,44257760000.0
Net Income From Continuing And Discontinued Operation,72361000000.0,72738000000.0,61271000000.0,44281000000.0
Total Expenses,123392000000.0,114887000000.0,98172000000.0,90056000000.0
Total Operating Income As Reported,88523000000.0,83383000000.0,69916000000.0,52959000000.0
Diluted Average Shares,7472000000.0,7540000000.0,7608000000.0,7683000000.0
Basic Average Shares,7446000000.0,7496000000.0,7547000000.0,7610000000.0
Diluted EPS,9.68,9.65,8.05,5.76
Basic EPS,9.72,9.7,8.12,5.82
Diluted NI Availto Com Stockholders,72361000000.0,72738000000.0,61271000000.0,44281000000.0
Net Income Common Stockholders,72361000000.0,72738000000.0,61271000000.0,44281000000.0
Net Income,72361000000.0,72738000000.0,61271000000.0,44281000000.0
Net Income Including Noncontrolling Interests,72361000000.0,72738000000.0,61271000000.0,44281000000.0
Net Income Continuous Operations,72361000000.0,72738000000.0,61271000000.0,44281000000.0
Tax Provision,16950000000.0,10978000000.0,9831000000.0,8755000000.0
Pretax Income,89311000000.0,83716000000.0,71102000000.0,53036000000.0
Other Income Expense,-238000000.0,302000000.0,1401000000.0,-12000000.0
Other Non Operating Income Expenses,-223000000.0,-32000000.0,98000000.0,-40000000.0
Special Income Charges,-30000000.0,-101000000.0,-13000000.0,-133000000.0
Write Off,30000000.0,101000000.0,13000000.0,133000000.0
Gain On Sale Of Security,15000000.0,435000000.0,1316000000.0,161000000.0
Net Non Operating Interest Income Expense,1026000000.0,31000000.0,-215000000.0,89000000.0
Interest Expense Non Operating,1968000000.0,2063000000.0,2346000000.0,2591000000.0
Interest Income Non Operating,2994000000.0,2094000000.0,2131000000.0,2680000000.0
Operating Income,88523000000.0,83383000000.0,69916000000.0,52959000000.0
Operating Expense,57529000000.0,52237000000.0,45940000000.0,43978000000.0
Research And Development,27195000000.0,24512000000.0,20716000000.0,19269000000.0
Selling General And Administration,30334000000.0,27725000000.0,25224000000.0,24709000000.0
Selling And Marketing Expense,22759000000.0,21825000000.0,20117000000.0,19598000000.0
General And Administrative Expense,7575000000.0,5900000000.0,5107000000.0,5111000000.0
Other Gand A,7575000000.0,5900000000.0,5107000000.0,5111000000.0
Gross Profit,146052000000.0,135620000000.0,115856000000.0,96937000000.0
Cost Of Revenue,65863000000.0,62650000000.0,52232000000.0,46078000000.0
Total Revenue,211915000000.0,198270000000.0,168088000000.0,143015000000.0
Operating Revenue,211915000000.0,198270000000.0,168088000000.0,143015000000.0

In [25]:
"""  
This is kind of a work area where i'm playing around and trying to see if I can get a good estimate of the tax ratem, turn out it works and I will use this with my calculations for the Return on Assets

"""
netIncomeMsft = msftIncomeStatement.loc["Net Income"][0]
pretaxincomemsft = msftIncomeStatement.loc["Pretax Income"][0]

print(f"{netIncomeMsft/1000000} \n{pretaxincomemsft/1000000} ")
1 - (netIncomeMsft/pretaxincomemsft)

72361.0
89311.0

0.18978625253328263

___

In [70]:
profitMargin = {}
debtToEquityRatio = {}
returnOnAssets = {}
quickRatio = {}


symbolsNotFoundInLoop = []

""" 
I realized that there are some stock that do not have a balnce sheet I guess for some reason. So I implemented some error handling into our code to handle that - JB

UPDATE
-------

I created a list of the companies that are no longer listed on the S&P 500. This should run without error but if for some reason the lenght of this list is > 0 than we will need to review the list
and make adjustments

"""

for c, r  in sp500.iterrows():
    companyBalanceSheet = yf.Ticker(r[0]).balance_sheet
    companyIncomeStatement = yf.Ticker(r[0]).income_stmt
    
    # print(companyBalanceSheet.index)
    try:
        #This try is becuase there is a small percentage of companies with 0 revenue and negative income, so we will just use a profit margin of 0 becuase they didnt make any revenues
        try:
            pm = companyIncomeStatement.loc["Net Income"][0]/companyIncomeStatement.loc["Total Revenue"][0]
            
            
        except:
            pm = 0
             
        dToE = companyBalanceSheet.loc["Total Liabilities Net Minority Interest"][0]/companyBalanceSheet.loc["Stockholders Equity"][0]
                        
        #Calculating the return on assets for the company
                
        avgAssets = (companyBalanceSheet.loc["Total Assets"][0] + companyBalanceSheet.loc["Total Assets"][1])/2
        roa = companyIncomeStatement.loc["Net Income"][0]/avgAssets
                        
        #Now its time to calculate the quick ratio, this one is a little more simple  
        try: #this try block is here becuase I realized that some companies dont have A.R. becuase thay have a factoring agreement
            qr = (companyBalanceSheet.loc["Cash Cash Equivalents And Short Term Investments"][0] + companyBalanceSheet.loc["Accounts Receivable"][0])/companyBalanceSheet.loc["Current Liabilities"][0]
        
        except:
            qr = (companyBalanceSheet.loc["Cash Cash Equivalents And Short Term Investments"][0])/companyBalanceSheet.loc["Current Liabilities"][0]
            
    except Exception as inst:
        print(r[0])
        print(yf.Ticker(r[0]).income_stmt)
        print("\n", inst.__annotations__)
        break
            
    
    #This is where I add the information we got into the dictionary for use in the function that will follow :)
    profitMargin[r.Symbol] = pm
    debtToEquityRatio[r.Symbol] = dToE
    returnOnAssets[r.Symbol] = roa
    quickRatio[r.Symbol] = qr

In [73]:
#Just making sure everything matches up
print(len(profitMargin), len(debtToEquityRatio), len(returnOnAssets), len(quickRatio), len(sp500))

385 385 385 385 385

Here is the list we get from the code block from below:

['ATVI', 'AET', 'AFL', 'ALXN', 'AGN', 'ADS', 'ALL', 'AXP', 'AIG', 'AMP', 'ABC', 'APC', 'ANDV', 'ANTM', 'ARNC', 'AIZ', 'BHGE', 'BLL', 'BAC', 'BBT', 'BRK.B', 'BHF', 'BF.B', 'CA', 'COG', 'COF', 'CBG', 'CBS', 'CELG', 'CTL', 'CERN', 'SCHW', 'CB', 'CI', 'XEC', 'CINF', 'C', 'CFG', 'CTXS', 'CMA', 'CXO', 'CSRA', 'DFS', 'DISCA', 'DISCK', 'DISH', 'DWDP', 'DPS', 'DRE', 'ETFC', 'EVHC', 'RE', 'ESRX', 'FB', 'FITB', 'FISV', 'FLIR', 'FBHS', 'GGP', 'GS', 'HRS', 'HIG', 'HUM', 'HBAN', 'INFO', 'JEC', 'JPM', 'KSU', 'KEY', 'LB', 'LLL', 'LUK', 'LNC', 'L', 'MTB', 'MET', 'KORS', 'MON', 'MS', 'MYL', 'NAVI', 'NFX', 'NLSN', 'NBL', 'NTRS', 'PBCT', 'PKI', 'PNC', 'PCLN', 'PFG', 'PGR', 'PRU', 'RJF', 'RTN', 'RHT', 'RF', 'COL', 'SCG', 'SNI', 'STT', 'SYMC', 'SYF', 'BK', 'TRV', 'TIF', 'TWX', 'TMK', 'TSS', 'USB', 'UTX', 'UNM', 'VAR', 'VIAB', 'WFC', 'HCN', 'WLTW', 'WYN', 'XLNX', 'XL', 'ZION']

In [ ]:
#Was using this to figure out which symbols we need to remove
# print(symbolsNotFound)
# #This is a good demonstration that there are some companies in this dataset that are no longer listed becuase of recent events
# stockData[stockData['Symbol'] == 'ATVI']

['ATVI', 'AET', 'AFL', 'ALXN', 'AGN', 'ADS', 'ALL', 'AXP', 'AIG', 'AMP', 'ABC', 'APC', 'ANDV', 'ANTM', 'ARNC', 'AIZ', 'BHGE', 'BLL', 'BAC', 'BBT', 'BRK.B', 'BHF', 'BF.B', 'CA', 'COG', 'COF', 'CBG', 'CBS', 'CELG', 'CTL', 'CERN', 'SCHW', 'CB', 'CI', 'XEC', 'CINF', 'C', 'CFG', 'CTXS', 'CMA', 'CXO', 'CSRA', 'DFS', 'DISCA', 'DISCK', 'DISH', 'DWDP', 'DPS', 'DRE', 'ETFC', 'EVHC', 'RE', 'ESRX', 'FB', 'FITB', 'FISV', 'FLIR', 'FBHS', 'GGP', 'GS', 'HRS', 'HIG', 'HUM', 'HBAN', 'INFO', 'JEC', 'JPM', 'KSU', 'KEY', 'LB', 'LLL', 'LUK', 'LNC', 'L', 'MTB', 'MET', 'KORS', 'MON', 'MS', 'MYL', 'NAVI', 'NFX', 'NLSN', 'NBL', 'NTRS', 'PBCT', 'PKI', 'PNC', 'PCLN', 'PFG', 'PGR', 'PRU', 'RJF', 'RTN', 'RHT', 'RF', 'COL', 'SCG', 'SNI', 'STT', 'SYMC', 'SYF', 'BK', 'TRV', 'TIF', 'TWX', 'TMK', 'TSS', 'USB', 'UTX', 'UNM', 'VAR', 'VIAB', 'WFC', 'HCN', 'WLTW', 'WYN', 'XLNX', 'XL', 'ZION']

In [74]:
#Changing the symbol into a index
sp500 = sp500.set_index('Symbol')

In [80]:
returnOnAssets

{'MMM': 2023-12-31   -0.144175
 2022-12-31     0.11907
 2021-12-31    0.122038
 2020-12-31     0.11231
 Name: Net Income, dtype: object,
 'AOS': 2023-12-31    0.170053
 2022-12-31    0.072011
 2021-12-31    0.148819
 2020-12-31    0.105374
 Name: Net Income, dtype: object,
 'ABT': 2023-12-31     0.07752
 2022-12-31     0.09391
 2021-12-31    0.095779
 2020-12-31    0.060886
 Name: Net Income, dtype: object,
 'ABBV': 2023-12-31    0.035559
 2022-12-31    0.086547
 2021-12-31    0.084397
 2020-12-31    0.033753
 Name: Net Income, dtype: object,
 'ACN': 2023-08-31    0.139512
 2022-08-31    0.139626
 2021-08-31    0.119925
 2020-08-31    0.103703
 Name: Net Income, dtype: object,
 'AYI': 2023-08-31    0.100454
 2022-08-31    0.111487
 2021-08-31    0.088928
 2020-08-31    0.072089
 Name: Net Income, dtype: object,
 'ADBE': 2023-11-30    0.190643
 2022-11-30    0.167041
 2021-11-30    0.169359
 2020-11-30    0.184743
 Name: Net Income, dtype: object,
 'AAP': 2023-12-31    0.002451
 2022-12-31    0.038281
 2021-12-31    0.049179
 2020-12-31     0.04064
 Name: Net Income, dtype: object,
 'AMD': 2023-12-31    0.012608
 2022-12-31    0.019488
 2021-12-31    0.046684
 2020-12-31    0.036762
 Name: Net Income, dtype: object,
 'AES': 2023-12-31    0.005988
 2022-12-31   -0.013131
 2021-12-31   -0.009836
 2020-12-31    0.001106
 Name: Net Income, dtype: object,
 'AMG': 2023-12-31    0.075014
 2022-12-31    0.127744
 2021-12-31    0.063064
 2020-12-31    0.022541
 Name: Net Income, dtype: object,
 'A': 2023-10-31    0.116459
 2022-10-31    0.117774
 2021-10-31    0.113642
 2020-10-31    0.067528
 Name: Net Income, dtype: object,
 'APD': 2023-09-30    0.077716
 2022-09-30    0.076226
 2021-09-30    0.070921
 2020-09-30    0.063745
 Name: Net Income, dtype: object,
 'AKAM': 2023-12-31    0.060168
 2022-12-31    0.057536
 2021-12-31    0.071595
 2020-12-31    0.061203
 Name: Net Income, dtype: object,
 'ALK': 2022-12-31    0.004123
 2021-12-31    0.033977
 2020-12-31   -0.094111
 Name: Net Income, dtype: object,
 'ALB': 2023-12-31    0.093306
 2022-12-31    0.159504
 2021-12-31    0.007334
 2020-12-31    0.022283
 Name: Net Income, dtype: object,
 'ARE': 2023-12-31    0.002867
 2022-12-31    0.014431
 2021-12-31    0.015803
 2020-12-31    0.021328
 Name: Net Income, dtype: object,
 'ALGN': 2023-12-31    0.073979
 2022-12-31    0.060103
 2021-12-31     0.12833
 2020-12-31    0.295198
 Name: Net Income, dtype: object,
 'ALLE': 2023-12-31    0.130175
 2022-12-31    0.110326
 2021-12-31    0.116348
 2020-12-31     0.07571
 Name: Net Income, dtype: object,
 'LNT': 2023-12-31    0.033961
 2022-12-31     0.03314
 2021-12-31     0.03256
 2020-12-31    0.030145
 Name: Net Income, dtype: object,
 'GOOGL': 2023-12-31    0.192261
 2022-12-31    0.156247
 2021-12-31    0.198091
 2020-12-31    0.104914
 Name: Net Income, dtype: object,
 'GOOG': 2023-12-31    0.192261
 2022-12-31    0.156247
 2021-12-31    0.198091
 2020-12-31    0.104914
 Name: Net Income, dtype: object,
 'MO': 2023-12-31    0.215296
 2022-12-31     0.15264
 2021-12-31    0.065542
 2020-12-31    0.118294
 Name: Net Income, dtype: object,
 'AMZN': 2023-12-31    0.061432
 2022-12-31   -0.005496
 2021-12-31    0.067366
 2020-12-31     0.04307
 Name: Net Income, dtype: object,
 'AEE': 2023-12-31    0.029263
 2022-12-31    0.027282
 2021-12-31    0.025148
 2020-12-31    0.022125
 Name: Net Income, dtype: object,
 'AAL': 2023-12-31    0.012866
 2022-12-31    0.001988
 2021-12-31   -0.031196
 2020-12-31   -0.139074
 Name: Net Income, dtype: object,
 'AEP': 2023-12-31    0.023232
 2022-12-31    0.024275
 2021-12-31    0.026178
 2020-12-31    0.023148
 Name: Net Income, dtype: object,
 'AMT': 2023-12-31    0.022268
 2022-12-31    0.026509
 2021-12-31    0.038548
 2020-12-31     0.02538
 Name: Net Income, dtype: object,
 'AWK': 2023-12-31    0.032504
 2022-12-31    0.028234
 2021-12-31    0.043488
 2020-12-31    0.024412
 Name: Net Income, dtype: object,
 'AME': 2023-12-31    0.095662
 2022-12-31     0.08447
 2021-12-31    0.072123
 2020-12-31    0.063555
 Name: Net Income, dtype: object,
 'AMGN': 2023-12-31    0.082785
 2022-12-31    0.080752
 2021-12-31     0.07263
 2020-12-31    0.089527
 Name: Net Income, dtype: object,
 'APH': 2023-12-31    0.121058
 2022-12-31    0.119444
 2021-12-31    0.099885
 2020-12-31    0.075561
 Name: Net Income, dtype: object,
 'ADI': 2023-10-31    0.066896
 2022-10-31    0.055472
 2021-10-31    0.028062
 2020-10-31    0.024638
 Name: Net Income, dtype: object,
 'ANSS': 2023-12-31    0.071432
 2022-12-31    0.074758
 2021-12-31    0.064897
 2020-12-31    0.061936
 Name: Net Income, dtype: object,
 'AON': 2023-12-31    0.076924
 2022-12-31    0.077674
 2021-12-31    0.037652
 2020-12-31    0.059073
 Name: Net Income, dtype: object,
 'APA': 2023-12-31     0.20112
 2022-12-31    0.253883
 2021-12-31    0.079955
 2020-12-31   -0.337008
 Name: Net Income, dtype: object,
 'AIV': 2023-12-31   -0.077831
 2022-12-31    0.035463
 2021-12-31   -0.002768
 2020-12-31   -0.002361
 Name: Net Income, dtype: object,
 'AAPL': 2023-09-30    0.275031
 2022-09-30    0.282993
 2021-09-30    0.268467
 2020-09-30     0.16279
 Name: Net Income, dtype: object,
 'AMAT': 2023-10-31    0.238656
 2022-10-31    0.227134
 2021-10-31     0.20496
 2020-10-31    0.125977
 Name: Net Income, dtype: object,
 'APTV': 2023-12-31    0.126881
 2022-12-31    0.025653
 2021-12-31     0.02548
 2020-12-31    0.077908
 Name: Net Income, dtype: object,
 'ADM': 2023-12-31    0.060889
 2022-12-31    0.075871
 2021-12-31    0.047358
 2020-12-31    0.030978
 Name: Net Income, dtype: object,
 'AJG': 2023-12-31    0.021551
 2022-12-31    0.024767
 2021-12-31    0.020157
 2020-12-31    0.018201
 Name: Net Income, dtype: object,
 'T': 2023-12-31    0.035559
 2022-12-31   -0.021049
 2021-12-31    0.049588
 2020-12-31   -0.012782
 Name: Net Income, dtype: object,
 'ADSK': 2023-01-31    0.091216
 2022-01-31    0.055085
 2021-01-31    0.133888
 Name: Net Income, dtype: object,
 'ADP': 2023-06-30    0.059839
 2022-06-30    0.051717
 2021-06-30    0.045572
 2020-06-30    0.043257
 Name: Net Income, dtype: object,
 'AZO': 2023-08-31    0.161763
 2022-08-31     0.15544
 2021-08-31    0.138852
 2020-08-31    0.110871
 Name: Net Income, dtype: object,
 'AVB': 2023-12-31    0.045159
 2022-12-31    0.055269
 2021-12-31    0.048828
 2020-12-31    0.040239
 Name: Net Income, dtype: object,
 'AVY': 2023-12-31    0.062251
 2022-12-31    0.093699
 2021-12-31    0.091595
 2020-12-31    0.068798
 Name: Net Income, dtype: object,
 'BAX': 2023-12-31    0.093913
 2022-12-31   -0.086028
 2021-12-31    0.045401
 2020-12-31    0.038965
 Name: Net Income, dtype: object,
 'BDX': 2023-09-30    0.028076
 2022-09-30    0.033657
 2021-09-30    0.039578
 2020-09-30    0.016535
 Name: Net Income, dtype: object,
 'BBY': 2024-01-31    0.080663
 2023-01-31    0.092233
 2022-01-31    0.159506
 2021-01-31    0.116867
 Name: Net Income, dtype: object,
 'BIIB': 2023-12-31     0.04518
 2022-12-31    0.118559
 2021-12-31     0.06055
 2020-12-31    0.155669
 Name: Net Income, dtype: object,
 'BLK': 2023-12-31     0.04569
 2022-12-31       0.043
 2021-12-31    0.049004
 2020-12-31    0.040957
 Name: Net Income, dtype: object,
 'HRB': 2023-06-30     0.17463
 2022-06-30    0.174622
 2021-04-30     0.18412
 2020-04-30   -0.002374
 Name: Net Income, dtype: object,
 'BA': 2023-12-31   -0.016212
 2022-12-31   -0.036007
 2021-12-31   -0.030659
 2020-12-31   -0.087125
 Name: Net Income, dtype: object,
 'BWA': 2023-12-31    0.039749
 2022-12-31    0.060038
 2021-12-31    0.034153
 2020-12-31      0.0318
 Name: Net Income, dtype: object,
 'BXP': 2023-12-31    0.007573
 2022-12-31      0.0338
 2021-12-31    0.020114
 2020-12-31    0.034747
 Name: Net Income, dtype: object,
 'BSX': 2023-12-31    0.047127
 2022-12-31    0.020649
 2021-12-31    0.030797
 2020-12-31   -0.002426
 Name: Net Income, dtype: object,
 'BMY': 2023-12-31    0.083603
 2022-12-31    0.065913
 2021-12-31    0.072862
 2020-12-31   -0.093917
 Name: Net Income, dtype: object,
 'AVGO': 2023-10-31    0.192759
 2022-10-31    0.157347
 2021-10-31    0.092205
 2020-10-31    0.040517
 Name: Net Income, dtype: object,
 'CHRW': 2023-12-31    0.058163
 2022-12-31    0.168254
 2021-12-31     0.15103
 2020-12-31    0.090595
 Name: Net Income, dtype: object,
 'CDNS': 2023-12-31    0.192687
 2022-12-31    0.157118
 2021-12-31    0.128802
 2020-12-31    0.109312
 Name: Net Income, dtype: object,
 'CPB': 2023-07-31    0.071649
 2022-07-31    0.063215
 2021-07-31    0.083674
 2020-07-31     0.13595
 Name: Net Income, dtype: object,
 'CAH': 2023-06-30     0.00598
 2022-06-30   -0.021376
 2021-06-30    0.013999
 2020-06-30   -0.084678
 Name: Net Income, dtype: object,
 'KMX': 2024-02-29    0.017955
 2023-02-28    0.018163
 2022-02-28    0.043136
 2021-02-28    0.027985
 Name: Net Income, dtype: object,
 'CCL': 2023-11-30   -0.001468
 2022-11-30   -0.120865
 2021-11-30   -0.188469
 2020-11-30   -0.203049
 Name: Net Income, dtype: object,
 'CAT': 2023-12-31    0.122005
 2022-12-31    0.079153
 2021-12-31    0.076603
 2020-12-31    0.035392
 Name: Net Income, dtype: object,
 'CBOE': 2023-12-31    0.105119
 2022-12-31    0.032444
 2021-12-31    0.073034
 2020-12-31     0.06464
 Name: Net Income, dtype: object,
 'CNC': 2023-12-31    0.033459
 2022-12-31    0.014884
 2021-12-31     0.01668
 2020-12-31    0.022389
 Name: Net Income, dtype: object,
 'CNP': 2023-12-31    0.023434
 2022-12-31    0.027012
 2021-12-31    0.037975
 2020-12-31   -0.019754
 Name: Net Income, dtype: object,
 'CF': 2023-12-31    0.110152
 2022-12-31    0.241684
 2021-12-31    0.066236
 2020-12-31    0.022897
 Name: Net Income, dtype: object,
 'CHTR': 2023-12-31    0.031243
 2022-12-31    0.034657
 2021-12-31    0.031908
 2020-12-31     0.02209
 Name: Net Income, dtype: object,
 'CHK': 2023-12-31     0.16211
 2022-12-31    0.330787
 2020-12-31   -0.652325
 Name: Net Income, dtype: object,
 'CVX': 2023-12-31    0.082293
 2022-12-31    0.136577
 2021-12-31    0.060172
 2020-12-31   -0.021346
 Name: Net Income, dtype: object,
 'CMG': 2023-12-31    0.164139
 2022-12-31    0.120105
 2021-12-31    0.087228
 2020-12-31    0.047525
 Name: Net Income, dtype: object,
 'CHD': 2023-12-31    0.089342
 2022-12-31    0.048939
 2021-12-31    0.097843
 2020-12-31    0.092925
 Name: Net Income, dtype: object,
 'CTAS': 2023-05-31      0.1615
 2022-05-31    0.148051
 2021-05-31    0.133101
 2020-05-31    0.104955
 Name: Net Income, dtype: object,
 'CSCO': 2023-07-31      0.1288
 2022-07-31     0.12062
 2021-07-31    0.108152
 2020-07-31    0.114514
 Name: Net Income, dtype: object,
 'CME': 2023-12-31    0.021233
 2022-12-31    0.017711
 2021-12-31    0.017351
 2020-12-31    0.013855
 Name: Net Income, dtype: object,
 'CMS': 2023-12-31    0.027347
 2022-12-31    0.025805
 2021-12-31    0.041714
 2020-12-31    0.023277
 Name: Net Income, dtype: object,
 'KO': 2023-12-31    0.112503
 2022-12-31    0.100196
 2021-12-31    0.102601
 2020-12-31    0.081348
 Name: Net Income, dtype: object,
 'CTSH': 2023-12-31    0.117022
 2022-12-31    0.126049
 2021-12-31    0.117628
 2020-12-31     0.07662
 Name: Net Income, dtype: object,
 'CL': 2023-12-31    0.143195
 2022-12-31    0.111132
 2021-12-31    0.134852
 2020-12-31    0.167787
 Name: Net Income, dtype: object,
 'CMCSA': 2023-12-31    0.058948
 2022-12-31    0.020571
 2021-12-31     0.05424
 2020-12-31    0.040354
 Name: Net Income, dtype: object,
 'CAG': 2023-05-31    0.030732
 2022-05-31     0.03993
 2021-05-31    0.058389
 2020-05-31    0.037768
 Name: Net Income, dtype: object,
 'COP': 2023-12-31    0.115487
 2022-12-31    0.196888
 2021-12-31    0.085153
 2020-12-31   -0.028469
 Name: Net Income, dtype: object,
 'ED': 2023-12-31    0.037209
 2022-12-31    0.024521
 2021-12-31    0.019882
 2020-12-31    0.016263
 Name: Net Income, dtype: object,
 'STZ': 2024-02-29     0.06861
 2023-02-28    -0.00282
 2022-02-28   -0.001605
 2021-02-28    0.079358
 Name: Net Income, dtype: object,
 'GLW': 2023-12-31    0.020035
 2022-12-31     0.04538
 2021-12-31    0.065725
 2020-12-31    0.017655
 Name: Net Income, dtype: object,
 'COST': 2023-08-31    0.094503
 2022-08-31    0.087774
 2021-08-31    0.075203
 2020-08-31    0.060108
 Name: Net Income, dtype: object,
 'COTY': 2023-06-30    0.041021
 2022-06-30    0.020946
 2021-06-30   -0.016248
 2020-06-30   -0.081259
 Name: Net Income, dtype: object,
 'CCI': 2023-12-31    0.038787
 2022-12-31    0.043255
 2021-12-31    0.028303
 2020-12-31     0.02727
 Name: Net Income, dtype: object,
 'CSX': 2023-12-31    0.088117
 2022-12-31    0.098814
 2021-12-31    0.089682
 2020-12-31    0.065583
 Name: Net Income, dtype: object,
 'CMI': 2023-12-31    0.023594
 2022-12-31    0.069049
 2021-12-31    0.068407
 2020-12-31    0.057428
 Name: Net Income, dtype: object,
 'CVS': 2023-12-31    0.034912
 2022-12-31    0.018038
 2021-12-31    0.033477
 2020-12-31    0.030037
 Name: Net Income, dtype: object,
 'DHI': 2023-09-30    0.150816
 2022-09-30    0.186149
 2021-09-30    0.132705
 2020-09-30    0.075435
 Name: Net Income, dtype: object,
 'DHR': 2023-12-31    0.056433
 2022-12-31    0.085395
 2021-12-31    0.076203
 2020-12-31    0.043189
 Name: Net Income, dtype: object,
 'DRI': 2023-05-31    0.096372
 2022-05-31    0.093516
 2021-05-31    0.061765
 2020-05-31   -0.005143
 Name: Net Income, dtype: object,
 'DVA': 2023-12-31    0.040893
 2022-12-31    0.033138
 2021-12-31    0.057859
 2020-12-31    0.045748
 Name: Net Income, dtype: object,
 'DE': 2023-10-31    0.104741
 2022-10-31    0.073471
 2021-10-31    0.061437
 2020-10-31    0.028344
 Name: Net Income, dtype: object,
 'DAL': 2023-12-31    0.063166
 2022-12-31    0.018063
 2021-12-31    0.003837
 2020-12-31   -0.169737
 Name: Net Income, dtype: object,
 'XRAY': 2023-12-31   -0.017585
 2022-12-31   -0.126557
 2021-12-31    0.054753
 2020-12-31   -0.009725
 Name: Net Income, dtype: object,
 'DVN': 2023-12-31    0.155442
 2022-12-31    0.249528
 2021-12-31    0.116695
 2020-12-31   -0.111178
 Name: Net Income, dtype: object,
 'DLR': 2023-12-31     0.02217
 2022-12-31    0.008825
 2021-12-31    0.039937
 2020-12-31    0.008327
 Name: Net Income, dtype: object,
 'DG': 2024-01-31    0.055488
 2023-01-31    0.080696
 2022-01-31    0.080136
 2021-01-31    0.088681
 Name: Net Income, dtype: object,
 'DLTR': 2024-01-31   -0.044328
 2023-01-31    0.071723
 2022-01-31    0.058958
 2021-01-31     0.05958
 Name: Net Income, dtype: object,
 'D': 2023-12-31    0.018651
 2022-12-31    0.012356
 2021-12-31    0.031792
 2020-12-31   -0.003751
 Name: Net Income, dtype: object,
 'DOV': 2023-12-31    0.095017
 2022-12-31    0.095786
 2021-12-31     0.10104
 2020-12-31    0.061448
 Name: Net Income, dtype: object,
 'DTE': 2023-12-31    0.031954
 2022-12-31    0.024772
 2021-12-31    0.020746
 2020-12-31    0.031291
 Name: Net Income, dtype: object,
 'DUK': 2023-12-31    0.016007
 2022-12-31    0.014367
 2021-12-31    0.022018
 2020-12-31    0.007758
 Name: Net Income, dtype: object,
 'DXC': 2023-03-31    -0.03157
 2022-03-31    0.039907
 2021-03-31   -0.008281
 Name: Net Income, dtype: object,
 'EMN': 2023-12-31    0.061024
 2022-12-31     0.05413
 2021-12-31    0.058498
 2020-12-31    0.032628
 Name: Net Income, dtype: object,
 'ETN': 2023-12-31    0.087629
 2022-12-31    0.067042
 2021-12-31    0.058383
 2020-12-31    0.038396
 Name: Net Income, dtype: object,
 'EBAY': 2023-12-31    0.130304
 2022-12-31    -0.05976
 2021-12-31    0.640829
 2020-12-31    0.266871
 Name: Net Income, dtype: object,
 'ECL': 2023-12-31     0.06337
 2022-12-31    0.050412
 2021-12-31    0.052176
 2020-12-31   -0.055649
 Name: Net Income, dtype: object,
 'EIX': 2023-12-31     0.01761
 2022-12-31    0.010313
 2021-12-31    0.011577
 2020-12-31    0.010901
 Name: Net Income, dtype: object,
 'EW': 2023-12-31    0.158861
 2022-12-31    0.172398
 2021-12-31    0.170268
 2020-12-31    0.093273
 Name: Net Income, dtype: object,
 'EA': 2023-03-31    0.058843
 2022-03-31    0.057889
 2021-03-31    0.061411
 Name: Net Income, dtype: object,
 'EMR': 2023-09-30    0.337142
 2022-09-30    0.082405
 2021-09-30    0.058737
 2020-09-30    0.050116
 Name: Net Income, dtype: object,
 'ETR': 2023-12-31    0.039938
 2022-12-31    0.018549
 2021-12-31    0.018913
 2020-12-31    0.023781
 Name: Net Income, dtype: object,
 'EOG': 2023-12-31    0.178204
 2022-12-31    0.182076
 2021-12-31    0.109448
 2020-12-31   -0.014197
 Name: Net Income, dtype: object,
 'EQT': 2023-12-31    0.072369
 2022-12-31    0.073859
 2021-12-31   -0.047659
 2020-12-31   -0.039987
 Name: Net Income, dtype: object,
 'EFX': 2023-12-31     0.04577
 2022-12-31    0.058436
 2021-12-31    0.062465
 2020-12-31    0.043655
 Name: Net Income, dtype: object,
 'EQIX': 2023-12-31    0.030786
 2022-12-31    0.022374
 2021-12-31    0.015889
 2020-12-31    0.011746
 Name: Net Income, dtype: object,
 'EQR': 2023-12-31     0.04151
 2022-12-31    0.038602
 2021-12-31    0.066224
 2020-12-31    0.045395
 Name: Net Income, dtype: object,
 'ESS': 2023-12-31    0.032815
 2022-12-31    0.033016
 2021-12-31    0.039504
 2020-12-31    0.045998
 Name: Net Income, dtype: object,
 'EL': 2023-06-30    0.045392
 2022-06-30     0.10784
 2021-06-30    0.129498
 2020-06-30    0.030863
 Name: Net Income, dtype: object,
 'ES': 2023-12-31   -0.008126
 2022-12-31    0.025815
 2021-12-31    0.022427
 2020-12-31    0.022145
 Name: Net Income, dtype: object,
 'EXC': 2023-12-31    0.023647
 2022-12-31    0.022042
 2021-12-31    0.017329
 2020-12-31     0.01994
 Name: Net Income, dtype: object,
 'EXPE': 2023-12-31    0.036896
 2022-12-31    0.016295
 2021-12-31    0.000556
 2020-12-31   -0.120918
 Name: Net Income, dtype: object,
 'EXPD': 2023-12-31    0.148876
 2022-12-31    0.268413
 2021-12-31    0.279901
 2020-12-31    0.137655
 Name: Net Income, dtype: object,
 'EXR': 2023-12-31    0.040541
 2022-12-31    0.043443
 2021-12-31    0.041775
 2020-12-31    0.024318
 Name: Net Income, dtype: object,
 'XOM': 2023-12-31    0.096621
 2022-12-31     0.14956
 2021-12-31     0.06182
 2020-12-31   -0.060211
 Name: Net Income, dtype: object,
 'FFIV': 2023-09-30    0.075053
 2022-09-30    0.061221
 2021-09-30    0.062946
 2020-09-30    0.058424
 Name: Net Income, dtype: object,
 'FAST': 2023-12-31    0.256339
 2022-12-31    0.241225
 2021-12-31    0.205293
 2020-12-31    0.190667
 Name: Net Income, dtype: object,
 'FRT': 2023-12-31    0.028432
 2022-12-31    0.046248
 2021-12-31    0.031373
 2020-12-31    0.015801
 Name: Net Income, dtype: object,
 'FDX': 2023-05-31    0.045883
 2022-05-31    0.044196
 2021-05-31    0.060426
 2020-05-31    0.014855
 Name: Net Income, dtype: object,
 'FIS': 2023-12-31   -0.112415
 2022-12-31   -0.282473
 2021-12-31    0.007045
 2020-12-31    0.002669
 Name: Net Income, dtype: object,
 'FE': 2023-12-31    0.023231
 2022-12-31    0.008559
 2021-12-31    0.027046
 2020-12-31    0.022746
 Name: Net Income, dtype: object,
 'FLS': 2023-12-31    0.037728
 2022-12-31    0.038121
 2021-12-31    0.025446
 2020-12-31    0.026349
 Name: Net Income, dtype: object,
 'FLR': 2023-12-31    0.020145
 2022-12-31    0.021014
 2021-12-31   -0.063768
 2020-12-31    -0.06305
 Name: Net Income, dtype: object,
 'FMC': 2023-12-31    0.114428
 2022-12-31    0.063773
 2021-12-31    0.064042
 2020-12-31    0.047832
 Name: Net Income, dtype: object,
 'FL': 2024-01-31    -0.04467
 2023-01-31    0.046294
 2022-01-31     0.12088
 2021-01-31    0.043723
 Name: Net Income, dtype: object,
 'F': 2023-12-31    0.016429
 2022-12-31   -0.007487
 2021-12-31     0.06779
 2020-12-31   -0.004834
 Name: Net Income, dtype: object,
 'FTV': 2023-12-31    0.052789
 2022-12-31    0.046045
 2021-12-31    0.037095
 2020-12-31    0.098365
 Name: Net Income, dtype: object,
 'BEN': 2023-09-30    0.030346
 2022-09-30    0.044409
 2021-09-30    0.062948
 2020-09-30    0.027462
 Name: Net Income, dtype: object,
 'FCX': 2023-12-31    0.035676
 2022-12-31     0.06695
 2021-12-31    0.083128
 2020-12-31    0.011564

In [79]:
# #Adding the new information, if we missed on in our function above than it will be null
def add_info(new_info: dict, columnName: str):
    for key, value in new_info.items():
        sp500.loc[key, columnName] = value
        
add_info(new_info = profitMargin, columnName = "profitMargin")
add_info(new_info = debtToEquityRatio,columnName = "debtToEquityRatio")
add_info(new_info = returnOnAssets, columnName = "returnOnAssets")
add_info(new_info = quickRatio,columnName =  "quickRatio")

ValueError: Incompatible indexer with Series

In [78]:
sp500

,Name,Sector,Price/Earnings,Earnings/Share,profitMargin,debtToEquityRatio,returnOnAssets
Symbol,,,,,,,
MMM,3M Company,Industrials,24.31,7.92,-0.214039,9.509465,NaN
AOS,A.O. Smith Corp,Industrials,27.76,1.70,0.144466,0.742518,NaN
ABT,Abbott Laboratories,Health Care,22.51,0.26,0.142686,0.890786,NaN
ABBV,AbbVie Inc.,Health Care,19.41,3.29,0.089528,11.999421,NaN
ACN,Accenture plc,Information Technology,25.47,5.44,0.107181,0.964732,NaN
...,...,...,...,...,...,...,...
XRX,Xerox Corp.,Information Technology,8.87,0.59,0.000145,2.629360,NaN
XYL,Xylem Inc.,Industrials,30.94,1.83,0.082700,0.583907,NaN
YUM,Yum! Brands Inc,Consumer Discretionary,27.25,4.07,0.225692,-1.792950,NaN
ZBH,Zimmer Biomet Holdings,Health Care,14.32,9.01,0.138487,0.721830,NaN
ZTS,Zoetis,Health Care,32.80,1.65,0.274345,1.860116,NaN

Okay this was just a test to see what we can do with our current dataset and the yahoo finance API. Now it's time to really get something crazy going. 
Also:
- Might help to get the information into the dataset and then export it to save processing speed